name: Deploy to Development Environment
on:
  push:
    branches:
       - main
  pull_request:
    branches:
       - Dev
env:
  
  AZURE_DEVWEBAPP_NAME: GitAc-Dev
  AZURE_PREPRODWEBAPP_NAME: GitAc-PreProd
#   AZURE_WEBAPP_PACKAGE_PATH: 'C:\actions-runner\_work\GitFinalAcTest\GitFinalAcTest\GitFinalAcTest\bin'
jobs:
  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore GitFinalAcTest/GitFinalAcTest.sln

    - name: build
      run: |
           msbuild GitFinalAcTest/GitFinalAcTest.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
    - name: publish
      run: |
           msbuild GitFinalAcTest/GitFinalAcTest.sln /t:Publish /p:Configuration=Release /p:Platform="Any CPU" /p:PublishDir="./artifacts"
   
      
      #--output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
      
#    - name: Upload artifacts
 #     uses: actions/upload-artifact@v2
  #    with:
   #     name: MyProject artifacts
    #    path: bin/Release
      
   # - name: Upload artifacts
    #  uses: actions/upload-artifact@v2
     # with:
      #      name: myapp
       #     path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
   
#   DeployDev:
#        name: Dev
#        needs: Build
#         if: github.event_name == 'refs/heads/master'
#        runs-on: self-hosted
#  #       env:
#  #         DEPLOYMENT_ENVIRONMENT: Dev
#  #         AZURE_DEVWEBAPP_NAME: GitAc-Dev
#  #         AZURE_PREPRODWEBAPP_NAME: GitAc-PreProd
#  #         AZURE_WEBAPP_PACKAGE_PATH: 'D:\a\GitFinalAcTest\GitFinalAcTest\bin\'
#        environment:
#            name: Dev
#        steps:
#         - name: Download artifacts
#          uses: actions/download-artifact@v2
#          # with:
#           # name: myapp
#            #path: artifacts/

#         - name: Deploy to IIS
#           run: |
#                # start-process PowerShell -verb runas 
#                iisreset /stop
#                Copy-Item C:\actions-runner2\_work\GitFinalTest\GitFinalTest\* C:\inetpub\wwwroot\GitFinalAcTest -Recurse -Force
#                iisreset /start
#           env:
#            WEBAPP_MSDeploy_USERNAME: ${{secrets.IIS_USERNAME}}
#            WEBAPP_MSDeploy_PASSWORD: ${{secrets.IIS_PASSWORD}}
